name: audio_graph_demo
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dart_audio_graph:
    path: ../../packages/dart_audio_graph

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
