name: flutter_coast_audio_miniaudio
description: An extension package for coast_audio using miniaudio.
version: 0.0.2
repository: https://github.com/SKKbySSK/coast_audio/tree/main/packages/flutter_coast_audio_miniaudio

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  coast_audio: ^0.0.3
  coast_audio_miniaudio: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_coast_audio_miniaudio
        pluginClass: FlutterCoastAudioMiniaudioPlugin
      ios:
        pluginClass: FlutterCoastAudioMiniaudioPlugin
      macos:
        pluginClass: FlutterCoastAudioMiniaudioPlugin
