name: audio_recorder
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^5.2.5
  flutter_media_metadata: ^1.0.0+1
  marquee_text: ^2.5.0+1
  flutter_coast_audio_miniaudio:
    path: ../../packages/flutter_coast_audio_miniaudio
  coast_audio_fft:
    path: ../../packages/coast_audio_fft
  path: ^1.8.2
  audio_session: ^0.1.13
  audio_service: ^0.18.9
  provider: ^6.0.5
  freezed_annotation: ^2.2.0
  permission_handler: ^10.2.0
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2

flutter:
  uses-material-design: true
